### ISSUE TITLE
Crash when remote user starts or stops sharing

### ISSUE THREAD

**Issue by gmoens-vuzix** [webex/webex-android-sdk#101]
Using SDK 3.2.1. This is very similar to previous crash I reported:

https://github.com/webex/webex-android-sdk/issues/83

But rather than crashing when you leave a meeting, the SDK is crashing when the remote user shares their screen, or stops sharing their screen. Sometimes it's the second time they share, sometimes the third.

2022-02-08 12:25:01.642 14609-14707/webex E/webex: JNI ERROR (app bug): accessed deleted Global 0x3006
2022-02-08 12:25:01.690 14609-14707/webex A/webex: java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x3006
2022-02-08 12:25:02.090 14609-14707/webex A/webex: runtime.cc:558] Runtime aborting...
2022-02-08 12:25:02.125 14609-14707/webex A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 14707 (Thread-1466), pid 14609 (webex)

I can't reproduce this with the kitchen sink app.

My app does a lot of switching out of render views and calls Call.setVideoRenderViews() and Call.setSharingRenderView() multiple times. The crash always seems to happen when calling one of these methods. Never the first time, but some time later during the call.

When I'm done with a render view, I try calling those two methods while passing in null, for example Call.setSharingRenderView(null) to try to clean up after myself. This does not seem to help. The docs say this:

"If is nil, it will update the video state as inactive to the server side."
"If is nil, it will update the content sharing state as inactive to the server side."

But I don't think this is true. When you decompile the SDK, you see this:

   public void setVideoRenderViews(@Nullable Pair videoRenderViews) {
      if (videoRenderViews == null) {
         this.logDebug(this.tag, "setVideoRenderViews: Do nothing.");

   public void setSharingRenderView(@Nullable View view) {
      if (view == null) {
         this.logDebug(this.tag, "setSharingRenderView: Do nothing.");

Passing in null does nothing in either case. This does not seem to match the docs.

I think cleaning up these old render views would help, but there does not appear to be a way to do that with the SDK.

**Comment by ankibatr** [comment]
Can you provide me full logs - with 3.3.0 version??

**Comment by ankibatr** [comment]
I have published snapshot version:
`implementation 'com.ciscowebex:androidsdk:3.3.0.1-SNAPSHOT@aar'`
Please use above snapshot version and check your cases for screen-share.
Now, you can pass null in `setSharingRenderView ` and `setVideoRenderViews ` API to remove the views from the SDK.

**Comment by gmoens-vuzix** [comment]
@ankibatr 

3.3.0.1-SNAPSHOT seems to have solved the problem after I put in calls to pass in null to setSharingRenderView and setVideoRenderViews when I'm done with those views.

Removing the null calls causes the app to start crashing again. Leaving the null calls and reverting back to 3.3.0 causes the app to start crashing again. So the combination of 3.3.0.1 and passing in null to those methods to clean up is working very well.

Looking forward to a stable release with these changes! I will test again when a stable release comes out.

**Comment by ankibatr** [comment]
Thanks @gmoens-vuzix for the confirmation.
