### ISSUE TITLE
Messages list API crash

### ISSUE THREAD

**Issue by Yanivox** [webex/webex-android-sdk#14]
Hello, 

I'm using the android Webex SDK, and since the last update when I'm making the messages list API call the app SDK crashes.

`client .messages().list(this.roomId, null, 50, null, result -> {}`

the error I get is 

`    com.cisco.spark.android.authenticator.NotAuthenticatedException`

But I'm already authorized and also able the make a video call to Webex's room

Thanks
Yaniv

**Comment by KunNiu** [comment]
Hello @Yanivox ,
Could you please provide some logs about your issue, it will help us locate the possible problem.
Thanks,
Nick

**Comment by krsboone** [comment]
Hi @Yanivox,

When using /messages related features, please ensure that `Phone.register` is invoked before doing so. Could you please give this a go, and let us know if you are still observing the issue?
