### ISSUE TITLE
Video fails to stream on latest release

### ISSUE THREAD

**Issue by mughalasim** [webex/webex-android-sdk#16]
Moving from the SDK version 2.3.0 to 2.4.0 fails video streaming capabilities. The Video is a blank screen although audio can be heard.
No changes within the app have been made and rolling back to 2.3.0 works seamlessly.

Using 
classpath 'com.android.tools.build:gradle:3.6.2'
classpath 'com.google.gms:google-services:4.3.3'

**Comment by kliu** [comment]
We released the 2.5 last week, please try it.

**Comment by mughalasim** [comment]
Thanks that worked :)
