### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [webex/webex-android-sdk#18]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by KunNiu** [comment]
Hi @Neustradamus , thanks for your suggestion. We will consider to change the library in a future version.

**Comment by Neustradamus** [comment]
@KunNiu: Thanks a lot!
- https://github.com/webex/webex-android-sdk/pull/24
- https://github.com/webex/webex-android-sdk/commit/4b9e996618dfd9c3d3e423c177ace1c6a118251a

In 2.6.0: https://github.com/webex/webex-android-sdk/releases/tag/2.6.0

**Comment by Neustradamus** [comment]
@KunNiu: There is a Bouncy Castle 1.66 since commit ;)
- http://bouncycastle.org/releasenotes.html
- http://bouncycastle.org/latest_releases.html
