### ISSUE TITLE
ERROR: Failed to resolve: com.ciscowebex:androidsdk:2.5.0

### ISSUE THREAD

**Issue by jatankshirsagar** [webex/webex-android-sdk#19]
ERROR: Failed to resolve: com.ciscowebex:androidsdk:2.5.0
Show in Project Structure dialog
Affected Modules: app

when adding 

compile('com.ciscowebex:androidsdk:2.5.0@aar', {
        transitive = true
    })

**Comment by KunNiu** [comment]
Hi @jatankshirsagar , have you added the maven repo url to your project's build.gradle file?
Does this issue happens with 2.4.0?

**Comment by jatankshirsagar** [comment]
Yes I have added the maven repo and also with 2.4.0 Am I missing something here ?

**Comment by jatankshirsagar** [comment]
Got it thanks I had put maven in buildScript instead of allprojects  issue is resolved
