### ISSUE TITLE
405 Method not allowed on register device

### ISSUE THREAD

**Issue by mughalasim** [webex/webex-android-sdk#26]
Updated to recent version of the Webex SDK
Gradle dependency is as follows

```
implementation('com.ciscowebex:androidsdk:2.5.0@aar', {
    transitive = true
})

```

Happens when a oauth authenticator uses saved credentials 

```
HTTP Error: WebexError[errorCode=-7001, message=405/Method Not Allowed/{"message":"Request method 'POST' not supported","errors":[{"description":"Request method 'POST' not supported"}],"trackingId":"CLIENT_772d762b-4007-406d-94c9-97a89b58f72c_1"}, ]
2020-07-04 13:53:18.036 27738-27738/com.refero.refero.staging E/WEBEX: FAILED TO REGISTER PHONE
```

We do believe it to be this section of the SDK that could be causing the issue

com.ciscowebex.androidsdk.phone.internal.RegisterOperation line 71
using POST instead of PUT specifically for updating existing devices

**Comment by KunNiu** [comment]
@mughalasim , this bug will fixed in 2.6.0, and before it released, you can use the version 2.6.0-SNAPSHOT.
Also you need to add SNAPSHOT maven to project build.gradle.
`maven {
            url 'https://devhub.cisco.com/artifactory/webexsdk-SNAPSHOT/'
        }
`
