### ISSUE TITLE
unable to import

### ISSUE THREAD

**Issue by girishalgundi** [webex/webex-android-sdk#31]
Hi Team,
unable to import this project into android studio, saying no module found
![image_2020_09_29T12_19_51_489Z](https://user-images.githubusercontent.com/20491332/94558959-2e3fcc80-027e-11eb-825d-159a70e50748.png)
I appreciate quick response
Thank you

**Comment by monika-carmatec** [comment]
Hi team, i'm not able to import OAuthWebViewAuthenticator and Webex class. I have added following as well, but still not working. Kindly help me to resolve this.
 compile('com.ciscowebex:androidsdk:2.6.0@aar', {
        transitive = true
    })

Thanks!

**Comment by KunNiu** [comment]
@girishalgundi , not sure what's your requirement. If you want to use SDK in your app, please follow the [install steps](https://github.com/webex/webex-android-sdk#install).

**Comment by KunNiu** [comment]
@monika-carmatec , have you add such maven repo to your project's gradle.build?
`maven {
            url 'https://devhub.cisco.com/artifactory/webexsdk/'
        }
`

**Comment by monika-carmatec** [comment]
Hi Nick,

Thanks for your quick response. Yes i have added everything that mentioned
in document. But still it's showing error only while i try to import
OAuthWebViewAuthenticator
and Webex class.

Thanks!

**Comment by girishalgundi** [comment]
In module I'm unable to find module name, hence not able to run the android sdk

**Comment by KunNiu** [comment]
@monika-carmatec , could you please try the demo app and see if it works on your side?
[Kitchensink](https://github.com/webex/webex-android-sdk-example)

**Comment by KunNiu** [comment]
@girishalgundi , SDK is a library project, you cannot run it directly.
