### ISSUE TITLE
MediaOption.setPin() doesn't appear to work

### ISSUE THREAD

**Issue by gmoens-vuzix** [webex/webex-android-sdk#37]
When attempting to dial a Webex meeting that requires a password, SDK 2.6.0 reports back error code HOST_PIN_OR_MEETING_PASSWORD_REQUIRED. Prompting the user for a host key or meeting password and setting it via MediaOption.setPin() does not appear to do anything because the SDK just keeps sending back the same error code and you cannot join the meeting. This issue is also seen in the Kitchen Sink app.

Steps to reproduce:

1. Schedule a Webex meeting on the website, making sure you require a password, and start it.
2. In the Kitchen Sink app, login and click the INITIATE CALL button.
3. Switch to the screen that let's you enter an "Address for dial".
4. Enter the meeting ID followed by "@webex.com".
5. Click the red button with the green phone icon.
6. When prompted, enter either host key or meeting password (full password or numeric password for video systems).
7. Click CONFIRM.
8. Noticed you are prompted for host key or meeting password again and you can't get past this screen.

**Comment by gmoens-vuzix** [comment]
#43

**Comment by adamrangs** [comment]
@gmoens-vuzix , please check `2.7.0.2-SNAPSHOT` and let us know if this works

**Comment by gmoens-vuzix** [comment]
> @gmoens-vuzix , please check `2.7.0.2-SNAPSHOT` and let us know if this works

Yes, the fix is working on my end with that snapshot.

**Comment by lcruz-pensare** [comment]
Hi everyone, I have the same issue with the last version of the sdk (2.7.0), Do you have an estimated date of release a version with fix this issue?

**Comment by krsboone** [comment]
@lcruz-pensare Release date for the next version has not been determined yet. In the meantime it is advised to use th erecent snapshot ```2.7.0.2-SNAPSHOT```
