### ISSUE TITLE
WebexError.getErrorMessage() does not return localized strings

### ISSUE THREAD

**Issue by gmoens-vuzix** [webex/webex-android-sdk#48]
WebexError.getErrorMessage() can return simple strings when errors happen internally within the SDK, such as "Device is not registered" or "permission deined" (note the misspelling).

WebexError.getErrorMessage() can also return a JSON response from the server with an embedded message property containing the error message.

In both cases, the messages are not localized for the device language. WebexError.getErrorCode() does not help in most cases as it is either ErrorCode.UNEXPECTED_ERROR or ErrorCode.SERVICE_ERROR, so these can't be used to pick a localized message for display.

**Comment by krsboone** [comment]
Hello, currently we don't support localization. Could you please submit this as a Feature Request [here](https://ciscocollabcustomer.ideas.aha.io/) for future consideration? Thank you!
