### ISSUE TITLE
Conversation not found error while initiate call

### ISSUE THREAD

**Issue by Ramaraju1992** [webex/webex-android-sdk#84]
@Team,
When i try to initiate a call in space with jwt authentication i am unable to start call for first time. ending up with the below error
`E/ServiceReqeust:263: OkHttp https://conv-k.wbx2.com/...  HTTP Error: WebexError[errorCode=SERVICE_ERROR, message=404/Not Found/{"errorCode":1404001,"message":"Conversation not found","errors":[{"errorCode":1404001,"description":"Conversation not found"}],"trackingId":"webex-android-sdk_9cce6edc-4712-41b4-9398-6f00a5fc7b4b_7"}, ]`
and when i debug got below error
`ResultImpl[_data=null, _error=WebexError[errorCode=SERVICE_ERROR, message=404/Not Found/{"errorCode":1404001,"message":"Conversation not found","errors":[{"errorCode":1404001,"description":"Conversation not found"}],"trackingId":"webex-android-sdk_490d3ca6-b677-4b5a-9efe-faaceea5acfd_7"}, ], ]`
**JWTAuthentication:**
`JWTAuthenticator jwtAuthenticator = new JWTAuthenticator();
jwtAuthenticator.authorize(jwt_token);`

**Webex instance:**
`Webex webex = new Webex(currentApplication, jwtAuthenticator);`

**Device Registration**(Success):
`

            webex.phone().register(new CompletionHandler<Void>() {
                @Override
                public void onComplete(Result<Void> result) {
                    try {
                        if (result.isSuccessful()) {
                            joinCall();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        onCallFailed();
                    }
                }
            });`

**Join/Initiate call**:
`

            private void joinCall() {
	          if (!TextUtils.isEmpty(spaceId)) {
			          webex.phone().dial(spaceId, MediaOption.audioVideo(local, remote), new CompletionHandler<Call>() {
				          @Override
				          public void onComplete(Result<Call> result) {
					          if (result.getError() != null) {
						          onCallFailed();
                                                         //Error is occuring here like result.data() == null
					          } else {
						          //call initial setup
					          }
				          }
			          });
	          } else {
		          onCallFailed();
	          }
          }`

**Comment by ralagana** [comment]
Hello, this error ("errorCode":1404001,"description":"Conversation not found") is usually thrown when the user who initiates the call is not part of the space being dialed. Given that you are using Jwt, this is likely the cause. Is the guest user added to the space/room? Can this user access that space through [/list-rooms](https://developer.webex.com/docs/api/v1/rooms/list-rooms) API (after exchanging that jwt for an access token), see [here](https://developer.webex.com/docs/guest-issuer#using-guest-tokens) how to do that)?

**Comment by Ramaraju1992** [comment]
@ralagana i found the cause for issue.
my actual integration was like below.

```
JWTAuthenticator jwtAuthenticator = new JWTAuthenticator();
jwtAuthenticator.authorize(jwt_token);
if (jwtAuthenticator.isAuthorized()) {
     Webex webex = new Webex(currentApplication, jwtAuthenticator);
}
```
when i change like below as per docs, it worked for me.
```
JWTAuthenticator jwtAuthenticator = new JWTAuthenticator();
Webex webex = new Webex(currentApplication, jwtAuthenticator);
jwtAuthenticator.authorize(jwt_token);
if (jwtAuthenticator.isAuthorized()) {
}
```
closing this as it seems the issue is fixed.
Thanks
