### ISSUE TITLE
Why does startShare always return false?

### ISSUE THREAD

**Issue by Jocerdikiawann** [webex/webex-android-sdk#99]
I want to run share screen but it always returns false

```kotlin
private fun startShareScreen() {
        Log.d(TAG, "shareScreen")

        val isSharing = isLocalSharing()
        Log.d(TAG, "shareScreen isSharing: $isSharing")
        if (!isSharing) {
//            updateScreenShareButtonState(ShareButtonState.DISABLED)
                getCalling()?.startSharing(CompletionHandler { result ->
                    Log.e("sharingScreenMe",result.isSuccessful.toString())
                })
        } else {
            getCalling()?.stopSharing(CompletionHandler { result ->
                Log.e("stopSharingScreenMe",result.isSuccessful.toString())
            })
        }
    }
```

**Comment by ralagana** [comment]
Hello, I used our latest KS Android SDK Demo App (https://github.com/webex/webex-android-sdk-example) to test this and I was able to confirm that _isSharing_ will return true once the user is actually sharing, which would be expected. Prior to user starting to cast, it will always be false, as expected.

This is my test showing that user was sharing in app and _isSharing_ being true in debug: https://www.evernote.com/shard/s375/sh/4470d194-195d-8742-26b5-a9e11558045f/3cdbff2911cb11b1ab07936781c16188

**Comment by Jocerdikiawann** [comment]
Can I ask for an example to do a share screen?
